name: Execute Files

on:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 8 * * *'
  workflow_dispatch:

env:
  cf_zone: ${{ vars.CF_ZONE }}
  port: ${{ vars.PORT }}
  cf_apitoken: ${{ secrets.CF_APITOKEN }}

jobs:
  executeFile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug
        run: env

      - name: Change permissions
        run: chmod +x ./AutomationAWS
        
      - name: Execute File at 23:00
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 23 * * *' }}
        run: ./AutomationAWS destroy  # 替换为您的可执行文件的路径和名称

      - name: Execute File at 8:00
        if: ${{ github.event_name == 'schedule' && github.event.schedule == '0 8 * * *' }}
        run: ./AutomationAWS create  # 替换为您的可执行文件的路径和名称
