name: Execute Files

on:
  schedule:
    - cron: '0 15 * * *'
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: actions to run
        required: false

env:
  cf_zone: ${{ vars.CF_ZONE }}
  port: ${{ vars.PORT }}
  cf_apitoken: ${{ secrets.CF_APITOKEN }}
  aws_key: ${{ secrets.AWS_KEY }}
  aws_secret: ${{ secrets.AWS_SECRET }}
  psk: ${{ secrets.PSK }}

jobs:
  executeFile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug
        run: env

      - name: Change permissions
        run: chmod +x ./AutomationAWS
        
      - name: Execute File at 23:00+8
        if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy') || (github.event_name == 'schedule' && github.event.schedule == '0 15 * * *') }}
        run: ./AutomationAWS destroy  # 替换为您的可执行文件的路径和名称

      - name: Execute File at 8:00+8
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'schedule' && github.event.schedule == '0 0 * * *') }}
        run: ./AutomationAWS create  # 替换为您的可执行文件的路径和名称
